services:
  - type: web
    name: mr-broker
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_HOST
        sync: false
      - key: AUTH_TOKEN
        generateValue: true
      - key: PORT
        value: 10000
